---
name:checks

on: [push]

jobs: 
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    staps:
      - name: login to Docker Hub 
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test 
        run: sudo docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: sudo docker-compose run --rm app sh -c "flake8"

